### PR TITLE
Community Call Meeting 04

### PR DESCRIPTION
**Pull request by arredr2**

### CODE REVIEW

**Comment by poojaranjan** [comment]
@arredr2 
Thanks for documenting notes. Suggestions to update:
- Please add the # to format the file in .md format
- Add a list of participants

**Comment by poojaranjan** [comment]
Please update "Previous meetings" (README file) [here](https://github.com/ethereum/pm/blob/master/Merge/merge.md)

**Comment by timbeiko** [comment]
@arredr2 this PR should only have the `.md` file, but it seems like there are two of them. Could you please remove the non `.md` file and update the README? thanks!

**Comment by arredr2** [comment]
@timbeiko. OK I just did it. Please let me know if there is anything wrong or any other questions!

**Comment by timbeiko** [comment]
Thanks @arredr2 !

**Pull request merged**
