### PR TITLE
Ethereum Core Devs Meeting 52 Notes

### LINKED ISSUE #69: Take notes for all core devs call 52
Hello,

We'd like someone to take notes on the all core devs call this Friday (#66). The call is typically 60-90 minutes. See sample notes from previous calls listed [here](https://github.com/ethereum/pm/blob/master/README.md). These notes are important and extremely helpful for later review, since the all core devs process is central to Ethereum governance.

You should attempt to transcribe as much of the content of the meeting as faithfully as you can. You should also record the list of meeting attendees. The meeting will be recorded, so you can refer back to the recording to finish the notes as necessary.

Notes should be posted as a PR on this repository, and are open for anyone to contribute to. Preliminary notes should be posted within 24 hours after the end of the meeting. Final notes with links to relevant documents, issues, and repositories, cross-referenced against the recording video with timed links, should be posted within a week after the end of the meeting.

Please do not hesitate to let me know if anything is unclear!

Thanks :)

Lane

### PR DESCRIPTION
**Pull request by annavladi**
Closes #69

### CODE REVIEW

**Comment by lrettig** [comment]
Thanks @annavladi! Followed up out-of-band about moving the body of the notes into a file.

**Comment by lrettig** [comment]
Thanks @annavladi! One final request. Can we add the agenda at the top of the document, and headers at the beginning of each section of the transcript when we move from one topic to the next? See [the previous meeting notes](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2051.md) for an example.

Lmk if you want a hand with this!

**Comment by annavladi** [comment]
@lrettig i did the updates you asked for and so I started formating it into actual notes, I am stuck on some stuff, just because its so new to me, I am not sure I got all the terms etc correctly, like EWASM update, so the stuff that I can't convert into status update, action items, decisions, I will leave as paragraphs.  There is a lot of good discussion there and I also feel that should stay as it is....let me know what you think pls

**Comment by lrettig** [comment]
I made a few final tweaks and merged! Thanks! We can continue to iterate on improving the notes with more PRs!

**Comment by annavladi** [comment]
@lrettig thank you!

**Pull request merged**
