### PR TITLE
Make it more obvious BUIDL is intended :)

### PR DESCRIPTION
**Pull request by xinbenlv**

### CODE REVIEW

**Comment by xinbenlv** [comment]
Replacing #47

**Comment by xinbenlv** [comment]
Thanks for approving. I didn't see any merging button, does it mean the merging needs to be conducted by a Ethereum teammate or should I do it elsewhere? (command-line, etc?)

**Comment by jamesray1** [comment]
It needs to be done by someone with write access such as @Souptacular.

**Comment by Souptacular** [comment]
Thank you!

**Pull request merged**
